// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Group4333.Models;

public partial class lab3Context : DbContext
{
    public lab3Context(DbContextOptions<lab3Context> options)
        : base(options)
    {
    }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.CodeClient);

            entity.Property(e => e.CodeClient)
               .IsRequired()
               .HasMaxLength(255)
               .IsFixedLength()
               .HasColumnName("code_client");
            entity.Property(e => e.DateBirsday)
                .HasColumnType("datetime")
                .HasColumnName("date_birsday");
            entity.Property(e => e.Email)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("email");
            entity.Property(e => e.Fio)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("fio");
            entity.Property(e => e.Home)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("home");
            entity.Property(e => e.Index)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("index");
            entity.Property(e => e.Kvartiva)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("kvartiva");
            entity.Property(e => e.Sity)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("sity");
            entity.Property(e => e.Street)
                .HasMaxLength(255)
                .IsFixedLength()
                .HasColumnName("street");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}