// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group4333.Models;

public partial class User
{

    public string Fio { get; set; }

    public string CodeClient { get; set; }

    public DateTime? DateBirsday { get; set; }

    public string Index { get; set; }

    public string Sity { get; set; }

    public string Street { get; set; }

    public string Home { get; set; }

    public string Kvartiva { get; set; }

    public string Email { get; set; }
}